<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.18.1
Pandas:  1.0.1


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [4]:
#ANSWER:
bikes = pd.read_table('bikeshare.csv' ,delimiter=',')
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [5]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [6]:
df = pd.read_excel('Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [7]:
#ANSWER
df.drop('Species_No', axis=1, inplace=True)
df

Petal_width  Petal_length  Sepal_width  Sepal_length Species_name
0            0.2           1.4          3.5           5.1       Setosa
1            0.2           1.4          3.0           4.9       Setosa
2            0.2           1.3          3.2           4.7       Setosa
3            0.2           1.5          3.1           4.6       Setosa
4            0.2           1.4          3.6           5.0       Setosa
..           ...           ...          ...           ...          ...
145          2.3           5.2          3.0           6.7    Verginica
146          1.9           5.0          2.5           6.3    Verginica
147          2.0           5.2          3.0           6.5    Verginica
148          2.3           5.4          3.4           6.2    Verginica
149          1.8           5.1          3.0           5.9    Verginica

[150 rows x 5 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [8]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

time  latitude  longitude  depth  mag magType  nst  \
0  2020-11-06T18:38:09.054Z   61.1028  -150.5262   46.7  2.9      ml  NaN   

   gap  dmin   rms  ...                   updated  \
0  NaN   NaN  0.66  ...  2020-11-06T18:52:22.646Z   

                                   place        type horizontalError  \
0  21 km NNE of Point Possession, Alaska  earthquake             NaN   

  depthError  magError  magNst     status  locationSource magSource  
0        0.6       NaN     NaN  automatic              ak        ak  

[1 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [9]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

[                             Bank Name               City  ST   CERT  \
 0                    Almena State Bank             Almena  KS  15426   
 1           First City Bank of Florida  Fort Walton Beach  FL  16748   
 2                 The First State Bank      Barboursville  WV  14361   
 3                   Ericson State Bank            Ericson  NE  18265   
 4     City National Bank of New Jersey             Newark  NJ  21111   
 ..                                 ...                ...  ..    ...   
 558                 Superior Bank, FSB           Hinsdale  IL  32646   
 559                Malta National Bank              Malta  OH   6629   
 560    First Alliance Bank & Trust Co.         Manchester  NH  34264   
 561  National State Bank of Metropolis         Metropolis  IL   3815   
 562                   Bank of Honolulu           Honolulu  HI  21029   
 
                    Acquiring Institution       Closing Date  
 0                            Equity Bank   October 23, 202

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [10]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [11]:
#ANSWER
print("Number of columns:",len(bikes.columns))
print("Number of rows:",len(bikes))

Number of columns: 17
Number of rows: 17379


What are the column names in `bikes`?

In [12]:
#ANSWER
for col in bikes.columns: 
    print(col)

instant
dteday
season
yr
mnth
hr
holiday
weekday
workingday
weathersit
temp
atemp
hum
windspeed
casual
registered
cnt


What are the data types of these columns?

In [13]:
#ANSWER
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     17379 non-null  int64  
 1   dteday      17379 non-null  object 
 2   season      17379 non-null  int64  
 3   yr          17379 non-null  int64  
 4   mnth        17379 non-null  int64  
 5   hr          17379 non-null  int64  
 6   holiday     17379 non-null  int64  
 7   weekday     17379 non-null  int64  
 8   workingday  17379 non-null  int64  
 9   weathersit  17379 non-null  int64  
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64  
 15  registered  17379 non-null  int64  
 16  cnt         17379 non-null  int64  
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


What is the (row) index for this DataFrame?

In [14]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [15]:
#ANSWER
print(bikes[['season']])

       season
0           1
1           1
2           1
3           1
4           1
...       ...
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]


How would we use object notation to show the first 4 rows of `atemp`?

In [16]:
#ANSWER
bikes.loc[:3,['atemp']]


atemp
0  0.2879
1  0.2727
2  0.2727
3  0.2879

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [17]:
#E: bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [18]:
#ANSWER
bikes.iloc[0:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [19]:
#ANSWER
bikes.iloc[:,1]

0        2011-01-01
1        2011-01-01
2        2011-01-01
3        2011-01-01
4        2011-01-01
            ...    
17374    2012-12-31
17375    2012-12-31
17376    2012-12-31
17377    2012-12-31
17378    2012-12-31
Name: dteday, Length: 17379, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [20]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [21]:
#ANSWER
bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [22]:
#ANSWER
bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

NaN can be used as a numerical value on mathematical operations, while None cannot.


ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [23]:
#ANSWER
def divide (dividend, divisor):
    if divisor == 0:
        quotient = np.nan
    else:
        quotient = dividend / divisor
    return (quotient)

print(divide(1,0))

nan


Apply the Pandas `isna` function to the following data objects:

In [24]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [25]:
#ANSWER
print("x is na: ", pd.isna(x))
print("y is na: ", pd.isna(y))

x is na:  False
y is na:  True


In [26]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [27]:
#ANSWER
np.isnan(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

#ANSWER: 

#read_csv(path, keep_default_na=False, na_values=["NA", "0"])

#na_values can be used to specify the type of data we want pandas to identify and overwrite (with - keep_default_na=False) as the I/O parameter.

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [28]:
#ANSWER
bikes['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [29]:
#ANSWER
print('range of instant:', bikes['instant'].min(), "to", bikes['instant'].max())
print('range of dteday:', bikes['dteday'].min(), "to", bikes['dteday'].max())
print('range of windspeed:', bikes['windspeed'].min(), "to", bikes['windspeed'].max())

range of instant: 1 to 17379
range of dteday: 2011-01-01 to 2012-12-31
range of windspeed: 0.0 to 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [30]:
bikes_min, bikes_max = (min(bikes.min(numeric_only = True)), max(bikes.max(numeric_only = True)))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [31]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [32]:
#ANSWER
bikes['atemp'].quantile((.1,.25,.5,.75,.9))

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [33]:
type(bikes['atemp'])

pandas.core.series.Series

In [34]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
10378    10379  2012-03-13       1   1     3  13        0        2   
14093    14094  2012-08-15       3   1     8  10        0        3   
14046    14047  2012-08-13       3   1     8  11        0        1   
11119    11120  2012-04-13       2   1     4  12        0        5   
13736    13737  2012-07-31       3   1     7  13        0        2   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
10378           1           1  0.60  0.6061  0.60     0.3881      53   
14093           1           2  0.72  0.6818  0.62     0.1940      70   
14046           1           1  0.76  0.6818  0.40     0.0896      94   
11119           1           1  0.50  0.4848  0.31     0.0000     104   
13736           1           1  0.80  0.7576  0.55     0.2836      69   

       registered  cnt  
10378         180  233  
14093         163  233  
14046         151  245  
11119         218  322  
13736         219  288

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [35]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [36]:
#ANSWER
#It is the group which the value of the row from column'atemp' belongs to after 
#segmenting all data in column 'atemp' into 4 bins

Here is a random sample of `atemp_level`:

In [37]:
atemp_level.sample(5)          

6501     (0.25, 0.5]
3461     (0.5, 0.75]
2108     (0.25, 0.5]
2415     (0.5, 0.75]
13228    (0.5, 0.75]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [38]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

5379     warm
14146    cool
16264    mild
24       mild
8518     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [39]:
#ANSWER
bikes['atemp_level'] = atemp_level

print(len(bikes.loc[(bikes['season']==2)&(bikes['atemp_level']=='mild')]))

1829


*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [40]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [41]:
# Cleaning Data
print("a")
print(a)
print(a.shape)
print("b")
print(b)
print(b.shape)
print("c")
print(c)
print(c.shape)
print("d")
print(d)
print(d.shape)
print("e")
print(e)
print(e.shape)

a
[0. 0. 0.]
(3,)
b
[[1. 1. 1.]]
(1, 3)
c
[[[5 5 1 1]
  [7 2 1 1]
  [8 2 8 3]]

 [[1 9 7 3]
  [7 2 2 9]
  [5 8 5 2]]]
(2, 3, 4)
d
[0 1 2 3]
(4,)
e
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


## Load Data

Load rock.csv and clean the dataset.

In [42]:
rock = pd.read_table('rock.csv' ,delimiter=',')
rock.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [43]:
rock.columns = rock.columns.str.replace('[?,*]','')
rock.columns = rock.columns.str.lower()
rock.head()

song clean artist clean release year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                combined  first  year  playcount  fg  
0        Caught Up in You by .38 Special      1     1         82  82  
1            Fantasy Girl by .38 Special      1     0          3   0  
2         Hold On Loosely by .38 Special      1     1         85  85  
3  Rockin' Into the Night by .38 Special      1     1         18  18  
4              Art For Arts Sake by 10cc      1     1          1   1

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [44]:
rock['release year'] = rock['release year'].fillna(0)
rock['release year'].isnull().sum()


0

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [45]:
rock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   song clean    2230 non-null   object
 1   artist clean  2230 non-null   object
 2   release year  2230 non-null   object
 3   combined      2230 non-null   object
 4   first         2230 non-null   int64 
 5   year          2230 non-null   int64 
 6   playcount     2230 non-null   int64 
 7   fg            2230 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 139.5+ KB


In [46]:
rock['release year'] = pd.to_numeric(rock['release year'].replace('SONGFACTS.COM',np.NaN))
rock.dtypes

song clean       object
artist clean     object
release year    float64
combined         object
first             int64
year              int64
playcount         int64
fg                int64
dtype: object

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [47]:
def min_max(df):
    print(df.describe().loc[['min','max']])
    
min_max(rock)

     release year  first  year  playcount     fg
min           0.0    1.0   0.0        0.0    0.0
max        2014.0    1.0   1.0      142.0  142.0


In [48]:
rock['release year'] = rock['release year'].replace(0,np.NaN)
min_max(rock)

rock['release year'] = rock['release year'].replace(1071,np.NaN)
min_max(rock)

     release year  first  year  playcount     fg
min        1071.0    1.0   0.0        0.0    0.0
max        2014.0    1.0   1.0      142.0  142.0
     release year  first  year  playcount     fg
min        1955.0    1.0   0.0        0.0    0.0
max        2014.0    1.0   1.0      142.0  142.0


# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [58]:
def take_row_info(df,row_no):
    print("song :",df.iloc[row_no]['song clean'])
    print("artist :",df.iloc[row_no]['artist clean'])
    print("release year :",df.iloc[row_no]['release year'])
    if df.iloc[row_no]['release year'] < 1970:
        print("release date is earlier than 1970")
    else:
        print("release date is later than 1970")
    

take_row_info(rock,3)    
    

song : Rockin' Into the Night
artist : .38 Special
release year : 1980.0
release date is later than 1970


## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [66]:
def df_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    return column

## Apply these functions to your dataset

In [67]:
rock.apply(df_to_float)


song clean  artist clean  release year  combined  first  year  \
0            NaN           NaN        1982.0       NaN      1     1   
1            NaN           NaN           NaN       NaN      1     0   
2            NaN           NaN        1981.0       NaN      1     1   
3            NaN           NaN        1980.0       NaN      1     1   
4            NaN           NaN        1975.0       NaN      1     1   
...          ...           ...           ...       ...    ...   ...   
2225         NaN           NaN           NaN       NaN      1     0   
2226         NaN           NaN        1981.0       NaN      1     1   
2227         NaN           NaN        1975.0       NaN      1     1   
2228         NaN           NaN        1983.0       NaN      1     1   
2229         NaN           NaN        1973.0       NaN      1     1   

      playcount   fg  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

## Describe the new float-only DataFrame.

In [68]:
rock.describe()

release year   first         year    playcount           fg
count   1651.000000  2230.0  2230.000000  2230.000000  2230.000000
mean    1978.569352     1.0     0.741256    16.872646    15.048430
std        9.309780     0.0     0.438043    25.302972    25.288366
min     1955.000000     1.0     0.000000     0.000000     0.000000
25%     1971.000000     1.0     0.000000     1.000000     0.000000
50%     1977.000000     1.0     1.000000     4.000000     3.000000
75%     1984.000000     1.0     1.000000    21.000000    18.000000
max     2014.000000     1.0     1.000000   142.000000   142.000000



> 
>
>




>


>


>




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



